export default function Accueil() {
  return (
    <div className="container-accueil">
      <div className="neige-presentation">
        <div className="neige">
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
          <div className="snow"></div>
        </div>
        <div className="presentation">
          <div className="presentation-Input">
            <h1>
              ASSOCIATION <br /> <span>Wild Christmas</span>
            </h1>
            <p>
              L'association "Wild Christmas" offre des cadeaux réconfortants aux
              plus démunis, incarnant un phare d'espoir pour la communauté
            </p>
            <div className="Input-button-logo">
              <input
                type="text"
                required
                minLength="4"
                maxLength="25"
                placeholder="Nom, Prenom"
              />

              <button type="button">GO →</button>
              <img src="/traineau.png" />
            </div>
          </div>
        </div>
      </div>
      <div className="Papa-noel">
        <img src="/Papa-Noel.png" />
      </div>
    </div>
  );
}
